[package]
name = "CodeAlpha"
version = "0.1.0"
description = "CodeAlpha"
authors = ["Adrian Hupka"]
license = ""
repository = ""
default-run = "CodeAlpha"
edition = "2021"
rust-version = "1.63"

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
tauri = { version = "1.0.0", features = ["clipboard", "macos-private-api", "notification", "process-command-api", "shell-sidecar", "system-tray", "window-close", "window-hide", "window-start-dragging"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
tokio = { version=  "1.17.0",features = ["full"] }
lazy_static = "1.4.0"
strum = { version = "0.24.1", features = ["derive"] }
diff = "0.1.13"
reqwest = { version = "0.11", features = ["json"] }
unicode-segmentation = "1.9.0"
parking_lot = "0.12.1"
unicode-segmentation = "1.9.0"
parking_lot = "0.12.1"

# macOS dependencies (crucial for Accessibility features to work)
core-foundation = "0.9.3"
core-graphics="0.22.3"
core-graphics-types = "0.1.1"
cocoa = "0.24.0"
objc = "0.2.7"

# Dependencies for accessibility apis
accessibility = { git = "https://github.com/Hupka/accessibility" }
accessibility-sys = { git = "https://github.com/Hupka/accessibility" }

# Miscellaneous
colored = "2" # Coloring console output
rand = "0.8.5" # Random number generator
enigo = "0.0.14" # Enigo keyboard library
rdev = "0.5.1"
ts-rs = {version = "6.2.0", features = ["serde-compat", "format", "uuid-impl"] }

# Parsing source files into syntax trees
tree-sitter = "0.20.0"
tree-sitter-swift = "=0.3.0"

window-shadows = "0.1.3"

[dev-dependencies]
pretty_assertions = "1.2.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]

# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
