name: Deploy
on:  [push]
jobs:
  Build:
    runs-on: macos-12
    timeout-minutes: 15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci --loglevel verbose
      - name: Build (MacOS Universal)
        run: |
          npm run build
      - run: echo "🍏 This job's status is ${{ job.status }}."
      